name: Optimize images

on: pull_request

jobs:
  compress-images:
    name: Compress repository images
    runs-on: ubuntu-latest
    if: |
       !contains(github.event.pull_request.title, '[skip ci]') &&
       !startsWith(github.head_ref, 'chore')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize with Calibre's image actions
        uses: calibreapp/image-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait images optimization
        run: sleep 120
